[package]
name = "rg"
version = "0.1.0"
edition = "2021"
description = "A linear algebra library for graphics that implements rotors instead of quaternions."
license = "LICENSE"
keywords = ["graphics", "linear algebra", "matrix", "vector", "rotor"]
categories = ["graphics"]

[dependencies]
